# Generated by Django 2.2.5 on 2019-10-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_ide',
            new_name='user_id',
        ),
    ]
